### ISSUE TITLE
(require 'subr-x)

### ISSUE THREAD

**Issue by phil-s** [Boruch-Baum/emacs-key-assist#2]
You're using `string-empty-p` so you need `subr-x`.

**Comment by Boruch-Baum** [comment]
On 2021-07-21 23:55, phil-s wrote:
>    You're using string-empty-p so you need subr-x.

Thanks! Resolved in commit 8e5cd08.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
